# Generated by Django 5.2.5 on 2025-09-03 13:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('gateway_type', models.CharField(choices=[('zarinpal', 'ZarinPal'), ('payping', 'PayPing'), ('idpay', 'IDPay'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20, verbose_name='Gateway Type')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Secret')),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Merchant ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='Is Sandbox')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Settings')),
                ('supported_currencies', models.JSONField(default=list, verbose_name='Supported Currencies')),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Transaction Fee (%)')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fixed Fee')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, default=50000000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='Payment ID')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cash_on_delivery', 'Cash on Delivery'), ('wallet', 'Digital Wallet')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='Currency')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Gateway Response')),
                ('gateway_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gateway Name')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gateway Transaction ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Refund Amount')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='Refund Reason')),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True, verbose_name='Card Last Four Digits')),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Card Brand')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Billing Address')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Refunded At')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=100, unique=True, verbose_name='Refund ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Refund Amount')),
                ('reason', models.TextField(verbose_name='Refund Reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Gateway Response')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order', verbose_name='Order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='payments_pa_user_id_be07d0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_pa_payment_5c92d7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment'], name='payments_re_payment_0f5ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order'], name='payments_re_order_i_891133_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['user'], name='payments_re_user_id_3d5301_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='payments_re_status_715c3a_idx'),
        ),
    ]
