/// کلاس ترجمه‌های اپلیکیشن
class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'fa': {
      // Shop App Specific
      'app_name': 'سینا شاپ',
      'welcome': 'خوش آمدید',
      'login': 'ورود',
      'register': 'ثبت نام',
      'logout': 'خروج',
      'email': 'ایمیل',
      'password': 'رمز عبور',
      'confirm_password': 'تایید رمز عبور',
      'forgot_password': 'رمز عبور خود را فراموش کرده‌اید؟',
      'remember_me': 'مرا به خاطر بسپار',
      'dont_have_account': 'حساب کاربری ندارید؟',
      'already_have_account': 'حساب کاربری دارید؟',
      'sign_up': 'ثبت نام',
      'sign_in': 'ورود',
      'home': 'خانه',
      'products': 'محصولات',
      'categories': 'دسته‌بندی‌ها',
      'cart': 'سبد خرید',
      'wishlist': 'علاقه‌مندی‌ها',
      'profile': 'پروفایل',
      'search': 'جستجو',
      'search_products': 'جستجو در محصولات...',
      'add_to_cart': 'افزودن به سبد خرید',
      'add_to_wishlist': 'افزودن به علاقه‌مندی‌ها',
      'remove_from_cart': 'حذف از سبد خرید',
      'remove_from_wishlist': 'حذف از علاقه‌مندی‌ها',
      'checkout': 'پرداخت',
      'orders': 'سفارشات',
      'order_history': 'تاریخچه سفارشات',
      'total': 'مجموع',
      'subtotal': 'مجموع فرعی',
      'tax': 'مالیات',
      'shipping': 'هزینه ارسال',
      'free_shipping': 'ارسال رایگان',
      'apply_coupon': 'اعمال کوپن',
      'coupon_code': 'کد کوپن',
      'specialOffers': 'پیشنهادات ویژه',
      'seeAll': 'مشاهده همه',
      'featuredProducts': 'محصولات ویژه',
      'new_arrivals': 'جدیدترین‌ها',
      'best_sellers': 'پرفروش‌ترین‌ها',
      'on_sale': 'در حراج',
      'out_of_stock': 'ناموجود',
      'in_stock': 'موجود',
      'quantity': 'تعداد',
      'price': 'قیمت',
      'rating': 'امتیاز',
      'reviews': 'نظرات',
      'description': 'توضیحات',
      'specifications': 'مشخصات',
      'delivery_info': 'اطلاعات ارسال',
      'return_policy': 'شرایط مرجوعی',
      'size': 'سایز',
      'color': 'رنگ',
      'brand': 'برند',
      'popularity': 'محبوبیت',
      'price_low_to_high': 'قیمت: کم به زیاد',
      'price_high_to_low': 'قیمت: زیاد به کم',
      'newest_first': 'جدیدترین‌ها اول',
      'oldest_first': 'قدیمی‌ترین‌ها اول',
      'no_items_found': 'موردی یافت نشد',
      'empty_cart': 'سبد خرید شما خالی است',
      'empty_wishlist': 'لیست علاقه‌مندی‌های شما خالی است',
      'no_orders': 'شما هنوز سفارشی ندارید',
      'network_error': 'خطای شبکه رخ داده است',
      'something_went_wrong': 'مشکلی پیش آمده است',
      'please_try_again': 'لطفاً دوباره تلاش کنید',
      'invalid_email': 'لطفاً یک آدرس ایمیل معتبر وارد کنید',
      'invalid_password': 'رمز عبور باید حداقل ۸ کاراکتر باشد',
      'passwords_dont_match': 'رمزهای عبور مطابقت ندارند',
      'field_required': 'این فیلد الزامی است',
      'item_added_to_cart': 'محصول به سبد خرید اضافه شد',
      'item_removed_from_cart': 'محصول از سبد خرید حذف شد',
      'item_added_to_wishlist': 'محصول به لیست علاقه‌مندی‌ها اضافه شد',
      'item_removed_from_wishlist': 'محصول از لیست علاقه‌مندی‌ها حذف شد',
      'order_placed_successfully': 'سفارش با موفقیت ثبت شد',
      'profile_updated': 'پروفایل با موفقیت به‌روزرسانی شد',
      'password_changed': 'رمز عبور با موفقیت تغییر کرد',

      // Universal App Translations
      'deviceLanguage': 'زبان دستگاه',
      'appTitle': 'سینا شاپ',
      'settings': 'تنظیمات',
      'language': 'زبان',
      'farsi': 'فارسی',
      'english': 'انگلیسی',
      'arabic': 'عربی',
      'russian': 'روسی',
      'chinese': 'چینی',
      'notifications': 'اعلان‌ها',
      'notificationsEnabled': 'اعلان‌ها فعال',
      'cancel': 'انصراف',
      'changeLanguage': 'تغییر زبان',
      'error': 'خطا',
      'general': 'عمومی',
      'connected': 'متصل شد',
      'disconnected': 'قطع اتصال',
      'nameLabel': 'نام',
      'ok': 'تایید',
      'default': 'پیش‌فرض',
      'sort': 'مرتب‌سازی',
      'edit': 'ویرایش',
      'delete': 'حذف',
      'close': 'بستن',
      'more': 'بیشتر',
      'loading': 'در حال بارگذاری...',
      'view': 'مشاهده',
      'name': 'نام',
      'add': 'افزودن',
      'systemMode': 'سیستم',
      'dark': 'تاریک',
      'light': 'روشن',
      'lightMode': 'حالت روشن',
      'darkMode': 'حالت تاریک',
      'theme': 'تم',
      'appTheme': 'تم برنامه',
      'aboutUs': 'درباره ما',
      'appVersion': 'نسخه برنامه',
      'yes': 'بله',
      'no': 'خیر',
      'save': 'ذخیره',
      'update': 'به‌روزرسانی',
      'refresh': 'تازه‌سازی',
      'retry': 'تلاش مجدد',
      'continue': 'ادامه',
      'back': 'برگشت',
      'next': 'بعدی',
      'previous': 'قبلی',
      'done': 'انجام شد',
      'clear': 'پاک کردن',
      'select': 'انتخاب',
      'selected': 'انتخاب شده',
      'all': 'همه',
      'none': 'هیچ‌کدام',
      'filter': 'فیلتر',
      'sort_by': 'مرتب‌سازی بر اساس',
      'date': 'تاریخ',
      'privacy_policy': 'سیاست حفظ حریم خصوصی',
      'terms_of_service': 'شرایط خدمات',
      'help_support': 'راهنما و پشتیبانی',
      'about': 'درباره',
      'version': 'نسخه',
      'success': 'موفقیت',
      'warning': 'هشدار',
      'info': 'اطلاعات',
      'tryAgain': 'تلاش مجدد',
      'unknown': 'نامشخص',

      // Profile specific translations
      'user_account': 'حساب کاربری',
      'edit_profile': 'ویرایش پروفایل',
      'edit_personal_info': 'تغییر اطلاعات شخصی',
      'my_addresses': 'آدرس‌های من',
      'manage_addresses': 'مدیریت آدرس‌های ارسال',
      'payment_cards': 'کارت‌های پرداخت',
      'manage_payment_methods': 'مدیریت روش‌های پرداخت',
      'my_orders': 'سفارش‌های من',
      'view_order_history': 'مشاهده تاریخچه خرید',
      'my_favorites': 'علاقه‌مندی‌ها',
      'favorite_products': 'محصولات مورد علاقه',
      'my_reviews': 'نظرات من',
      'submitted_reviews': 'نظرات ثبت شده',
      'notification_settings': 'تنظیمات اطلاع‌رسانی',
      'toggle_dark_mode': 'حالت تاریک',
      'switch_to_light_mode': 'تغییر به حالت روشن',
      'switch_to_dark_mode': 'تغییر به حالت تاریک',
      'language_selection': 'انتخاب زبان',
      'theme_settings': 'تنظیمات تم',
      'logout_dialog_title': 'خروج از حساب',
      'logout_dialog_content':
          'آیا مطمئن هستید که می‌خواهید از حساب کاربری خود خارج شوید؟',

      // Products & Categories & Cart specific translations
      'all_categories': 'همه دسته‌بندی‌ها',
      'products_in_category': 'محصول در این دسته',
      'filter_products': 'فیلتر محصولات',
      'sort_products': 'مرتب‌سازی محصولات',
      'apply_filter': 'اعمال فیلتر',
      'clear_filter': 'پاک کردن فیلتر',
      'price_range': 'محدوده قیمت',
      'min_price': 'حداقل قیمت',
      'max_price': 'حداکثر قیمت',
      'brands': 'برندها',
      'colors': 'رنگ‌ها',
      'sizes': 'سایزها',
      'rating_filter': 'حداقل امتیاز',
      'only_in_stock': 'فقط موجود',
      'only_on_sale': 'فقط تخفیف‌دار',
      'product_details': 'جزئیات محصول',
      'related_products': 'محصولات مرتبط',
      'customer_reviews': 'نظرات مشتریان',
      'write_review': 'نوشتن نظر',
      'add_to_favorites': 'افزودن به علاقه‌مندی‌ها',
      'share_product': 'اشتراک‌گذاری محصول',
      'select_color': 'انتخاب رنگ',
      'select_size': 'انتخاب سایز',
      'increase_quantity': 'افزایش تعداد',
      'decrease_quantity': 'کاهش تعداد',
      'shopping_cart': 'سبد خرید',
      'your_cart': 'سبد خرید شما',
      'clear_all': 'پاک کردن همه',
      'order_summary': 'خلاصه سفارش',
      'free_shipping_on_orders_over':
          'ارسال رایگان برای سفارش‌های بالای ۱۰۰ دلار',
      'your_cart_is_empty': 'سبد خرید شما خالی است',
      'add_items_to_get_started': 'برای شروع، محصولاتی به سبد خرید اضافه کنید',
      'cart_updated': 'سبد خرید به‌روزرسانی شد',
      'clear_cart': 'پاک کردن سبد خرید',
      'are_you_sure_clear_cart':
          'آیا مطمئن هستید که می‌خواهید سبد خرید را پاک کنید؟',
      'cart_cleared': 'سبد خرید پاک شد',
      'checkout_coming_soon': 'پرداخت به زودی در دسترس خواهد بود',
      'cart_is_empty': 'سبد خرید خالی است',
      'start_shopping': 'شروع خرید',
      'cart_summary': 'خلاصه سفارش',
      'items_count': 'تعداد اقلام',
      'shipping_fee': 'هزینه ارسال',
      'discount_amount': 'مبلغ تخفیف',
      'final_price': 'قیمت نهایی',
      'proceed_to_checkout': 'ادامه برای پرداخت',
      'update_cart': 'بروزرسانی سبد',
      'continue_shopping': 'ادامه خرید',
      'save_for_later': 'ذخیره برای بعد',
      'move_to_wishlist': 'انتقال به علاقه‌مندی‌ها',
    },
    'en': {
      // Shop App Specific
      'app_name': 'Sina Shop',
      'welcome': 'Welcome',
      'login': 'Login',
      'register': 'Register',
      'logout': 'Logout',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot your password?',
      'remember_me': 'Remember me',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'sign_up': 'Sign Up',
      'sign_in': 'Sign In',
      'home': 'Home',
      'products': 'Products',
      'categories': 'Categories',
      'cart': 'Cart',
      'wishlist': 'Wishlist',
      'profile': 'Profile',
      'search': 'Search',
      'search_products': 'Search products...',
      'add_to_cart': 'Add to Cart',
      'add_to_wishlist': 'Add to Wishlist',
      'remove_from_cart': 'Remove from Cart',
      'remove_from_wishlist': 'Remove from Wishlist',
      'checkout': 'Checkout',
      'orders': 'Orders',
      'order_history': 'Order History',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'tax': 'Tax',
      'shipping': 'Shipping',
      'free_shipping': 'Free Shipping',
      'apply_coupon': 'Apply Coupon',
      'coupon_code': 'Coupon Code',
      'specialOffers': 'Special Offers',
      'seeAll': 'See All',
      'featuredProducts': 'Featured Products',
      'new_arrivals': 'New Arrivals',
      'best_sellers': 'Best Sellers',
      'on_sale': 'On Sale',
      'out_of_stock': 'Out of Stock',
      'in_stock': 'In Stock',
      'quantity': 'Quantity',
      'price': 'Price',
      'rating': 'Rating',
      'reviews': 'Reviews',
      'description': 'Description',
      'specifications': 'Specifications',
      'delivery_info': 'Delivery Information',
      'return_policy': 'Return Policy',
      'size': 'Size',
      'color': 'Color',
      'brand': 'Brand',
      'popularity': 'Popularity',
      'price_low_to_high': 'Price: Low to High',
      'price_high_to_low': 'Price: High to Low',
      'newest_first': 'Newest First',
      'oldest_first': 'Oldest First',
      'no_items_found': 'No items found',
      'empty_cart': 'Your cart is empty',
      'empty_wishlist': 'Your wishlist is empty',
      'no_orders': 'You have no orders yet',
      'network_error': 'Network error occurred',
      'something_went_wrong': 'Something went wrong',
      'please_try_again': 'Please try again',
      'invalid_email': 'Please enter a valid email address',
      'invalid_password': 'Password must be at least 8 characters',
      'passwords_dont_match': "Passwords don't match",
      'field_required': 'This field is required',
      'item_added_to_cart': 'Item added to cart',
      'item_removed_from_cart': 'Item removed from cart',
      'item_added_to_wishlist': 'Item added to wishlist',
      'item_removed_from_wishlist': 'Item removed from wishlist',
      'order_placed_successfully': 'Order placed successfully',
      'profile_updated': 'Profile updated successfully',
      'password_changed': 'Password changed successfully',

      // Universal App Translations
      'deviceLanguage': 'Device Language',
      'appTitle': 'Sina Shop',
      'settings': 'Settings',
      'language': 'Language',
      'farsi': 'Persian',
      'english': 'English',
      'arabic': 'Arabic',
      'russian': 'Russian',
      'chinese': 'Chinese',
      'notifications': 'Notifications',
      'notificationsEnabled': 'Notifications Enabled',
      'cancel': 'Cancel',
      'changeLanguage': 'Change Language',
      'error': 'Error',
      'general': 'General',
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'nameLabel': 'Name',
      'ok': 'OK',
      'default': 'Default',
      'sort': 'Sort',
      'edit': 'Edit',
      'delete': 'Delete',
      'close': 'Close',
      'more': 'More',
      'loading': 'Loading...',
      'view': 'View',
      'name': 'Name',
      'add': 'Add',
      'systemMode': 'System',
      'dark': 'Dark',
      'light': 'Light',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'theme': 'Theme',
      'appTheme': 'App Theme',
      'aboutUs': 'About Us',
      'appVersion': 'App Version',
      'yes': 'Yes',
      'no': 'No',
      'save': 'Save',
      'update': 'Update',
      'refresh': 'Refresh',
      'retry': 'Retry',
      'continue': 'Continue',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'done': 'Done',
      'clear': 'Clear',
      'select': 'Select',
      'selected': 'Selected',
      'all': 'All',
      'none': 'None',
      'filter': 'Filter',
      'sort_by': 'Sort by',
      'date': 'Date',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'help_support': 'Help & Support',
      'about': 'About',
      'version': 'Version',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Information',
      'tryAgain': 'Try Again',
      'unknown': 'Unknown',

      // Profile specific translations
      'user_account': 'User Account',
      'edit_profile': 'Edit Profile',
      'edit_personal_info': 'Change Personal Information',
      'my_addresses': 'My Addresses',
      'manage_addresses': 'Manage Shipping Addresses',
      'payment_cards': 'Payment Cards',
      'manage_payment_methods': 'Manage Payment Methods',
      'my_orders': 'My Orders',
      'view_order_history': 'View Purchase History',
      'my_favorites': 'Favorites',
      'favorite_products': 'Favorite Products',
      'my_reviews': 'My Reviews',
      'submitted_reviews': 'Submitted Reviews',
      'notification_settings': 'Notification Settings',
      'toggle_dark_mode': 'Dark Mode',
      'switch_to_light_mode': 'Switch to Light Mode',
      'switch_to_dark_mode': 'Switch to Dark Mode',
      'language_selection': 'Language Selection',
      'theme_settings': 'Theme Settings',
      'logout_dialog_title': 'Logout',
      'logout_dialog_content':
          'Are you sure you want to logout from your account?',
    },
    'ar': {
      // Shop App Specific
      'app_name': 'متجر سينا',
      'welcome': 'مرحباً',
      'login': 'تسجيل الدخول',
      'register': 'التسجيل',
      'logout': 'تسجيل الخروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'remember_me': 'تذكرني',
      'dont_have_account': 'ليس لديك حساب؟',
      'already_have_account': 'لديك حساب بالفعل؟',
      'sign_up': 'التسجيل',
      'sign_in': 'تسجيل الدخول',
      'home': 'الرئيسية',
      'products': 'المنتجات',
      'categories': 'الفئات',
      'cart': 'السلة',
      'wishlist': 'قائمة الأمنيات',
      'profile': 'الملف الشخصي',
      'search': 'بحث',
      'search_products': 'البحث في المنتجات...',
      'add_to_cart': 'إضافة إلى السلة',
      'add_to_wishlist': 'إضافة إلى قائمة الأمنيات',
      'remove_from_cart': 'إزالة من السلة',
      'remove_from_wishlist': 'إزالة من قائمة الأمنيات',
      'checkout': 'الدفع',
      'orders': 'الطلبات',
      'order_history': 'تاريخ الطلبات',
      'total': 'المجموع',
      'subtotal': 'المجموع الفرعي',
      'tax': 'الضريبة',
      'shipping': 'الشحن',
      'free_shipping': 'شحن مجاني',
      'apply_coupon': 'تطبيق الكوبون',
      'coupon_code': 'رمز الكوبون',
      'featured_products': 'المنتجات المميزة',
      'new_arrivals': 'الوافدون الجدد',
      'best_sellers': 'الأكثر مبيعاً',
      'on_sale': 'في التخفيض',
      'out_of_stock': 'نفد من المخزون',
      'in_stock': 'متوفر',
      'quantity': 'الكمية',
      'price': 'السعر',
      'rating': 'التقييم',
      'reviews': 'المراجعات',
      'description': 'الوصف',
      'specifications': 'المواصفات',
      'delivery_info': 'معلومات التسليم',
      'return_policy': 'سياسة الإرجاع',
      'size': 'المقاس',
      'color': 'اللون',
      'brand': 'العلامة التجارية',
      'popularity': 'الشعبية',
      'price_low_to_high': 'السعر: من المنخفض إلى المرتفع',
      'price_high_to_low': 'السعر: من المرتفع إلى المنخفض',
      'newest_first': 'الأحدث أولاً',
      'oldest_first': 'الأقدم أولاً',
      'no_items_found': 'لم يتم العثور على عناصر',
      'empty_cart': 'سلتك فارغة',
      'empty_wishlist': 'قائمة أمنياتك فارغة',
      'no_orders': 'ليس لديك طلبات حتى الآن',
      'network_error': 'حدث خطأ في الشبكة',
      'something_went_wrong': 'حدث خطأ ما',
      'please_try_again': 'يرجى المحاولة مرة أخرى',
      'invalid_email': 'يرجى إدخال عنوان بريد إلكتروني صالح',
      'invalid_password': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
      'passwords_dont_match': 'كلمات المرور غير متطابقة',
      'field_required': 'هذا الحقل مطلوب',
      'item_added_to_cart': 'تمت إضافة العنصر إلى السلة',
      'item_removed_from_cart': 'تمت إزالة العنصر من السلة',
      'item_added_to_wishlist': 'تمت إضافة العنصر إلى قائمة الأمنيات',
      'item_removed_from_wishlist': 'تمت إزالة العنصر من قائمة الأمنيات',
      'order_placed_successfully': 'تم تقديم الطلب بنجاح',
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح',
      'password_changed': 'تم تغيير كلمة المرور بنجاح',

      // Universal App Translations
      'deviceLanguage': 'لغة الجهاز',
      'appTitle': 'متجر سينا',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'farsi': 'الفارسية',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'russian': 'الروسية',
      'chinese': 'الصينية',
      'notifications': 'الإشعارات',
      'notificationsEnabled': 'الإشعارات مفعلة',
      'cancel': 'إلغاء',
      'changeLanguage': 'تغيير اللغة',
      'error': 'خطأ',
      'general': 'عام',
      'connected': 'متصل',
      'disconnected': 'غير متصل',
      'nameLabel': 'الاسم',
      'ok': 'موافق',
      'default': 'افتراضي',
      'sort': 'ترتيب',
      'edit': 'تعديل',
      'delete': 'حذف',
      'close': 'إغلاق',
      'more': 'المزيد',
      'loading': 'جاري التحميل...',
      'view': 'عرض',
      'name': 'الاسم',
      'add': 'إضافة',
      'systemMode': 'النظام',
      'dark': 'مظلم',
      'light': 'مضيء',
      'lightMode': 'الوضع الفاتح',
      'darkMode': 'الوضع الداكن',
      'theme': 'السمة',
      'appTheme': 'سمة التطبيق',
      'aboutUs': 'من نحن',
      'appVersion': 'إصدار التطبيق',
      'yes': 'نعم',
      'no': 'لا',
      'save': 'حفظ',
      'update': 'تحديث',
      'refresh': 'تحديث',
      'retry': 'إعادة المحاولة',
      'continue': 'متابعة',
      'back': 'رجوع',
      'next': 'التالي',
      'previous': 'السابق',
      'done': 'تم',
      'clear': 'مسح',
      'select': 'اختيار',
      'selected': 'مختار',
      'all': 'الكل',
      'none': 'لا شيء',
      'filter': 'فلتر',
      'sort_by': 'ترتيب حسب',
      'date': 'التاريخ',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_of_service': 'شروط الخدمة',
      'help_support': 'المساعدة والدعم',
      'about': 'حول',
      'version': 'الإصدار',
      'success': 'نجح',
      'warning': 'تحذير',
      'info': 'معلومات',
      'tryAgain': 'إعادة المحاولة',
      'unknown': 'غير معروف',
    },
    'ru': {
      // Shop App Specific
      'app_name': 'Магазин Сина',
      'welcome': 'Добро пожаловать',
      'login': 'Войти',
      'register': 'Регистрация',
      'logout': 'Выйти',
      'email': 'Электронная почта',
      'password': 'Пароль',
      'confirm_password': 'Подтвердите пароль',
      'forgot_password': 'Забыли пароль?',
      'remember_me': 'Запомнить меня',
      'dont_have_account': 'Нет аккаунта?',
      'already_have_account': 'Уже есть аккаунт?',
      'sign_up': 'Регистрация',
      'sign_in': 'Войти',
      'home': 'Главная',
      'products': 'Товары',
      'categories': 'Категории',
      'cart': 'Корзина',
      'wishlist': 'Список желаний',
      'profile': 'Профиль',
      'search': 'Поиск',
      'search_products': 'Поиск товаров...',
      'add_to_cart': 'Добавить в корзину',
      'add_to_wishlist': 'Добавить в избранное',
      'remove_from_cart': 'Удалить из корзины',
      'remove_from_wishlist': 'Удалить из избранного',
      'checkout': 'Оформить заказ',
      'orders': 'Заказы',
      'order_history': 'История заказов',
      'total': 'Итого',
      'subtotal': 'Подытог',
      'tax': 'Налог',
      'shipping': 'Доставка',
      'free_shipping': 'Бесплатная доставка',
      'apply_coupon': 'Применить купон',
      'coupon_code': 'Код купона',
      'featured_products': 'Рекомендуемые товары',
      'new_arrivals': 'Новинки',
      'best_sellers': 'Хиты продаж',
      'on_sale': 'Со скидкой',
      'out_of_stock': 'Нет в наличии',
      'in_stock': 'В наличии',
      'quantity': 'Количество',
      'price': 'Цена',
      'rating': 'Рейтинг',
      'reviews': 'Отзывы',
      'description': 'Описание',
      'specifications': 'Характеристики',
      'delivery_info': 'Информация о доставке',
      'return_policy': 'Политика возврата',
      'size': 'Размер',
      'color': 'Цвет',
      'brand': 'Бренд',
      'popularity': 'Популярность',
      'price_low_to_high': 'Цена: по возрастанию',
      'price_high_to_low': 'Цена: по убыванию',
      'newest_first': 'Сначала новые',
      'oldest_first': 'Сначала старые',
      'no_items_found': 'Товары не найдены',
      'empty_cart': 'Ваша корзина пуста',
      'empty_wishlist': 'Ваш список желаний пуст',
      'no_orders': 'У вас пока нет заказов',
      'network_error': 'Ошибка сети',
      'something_went_wrong': 'Что-то пошло не так',
      'please_try_again': 'Пожалуйста, попробуйте еще раз',
      'invalid_email': 'Введите действительный адрес электронной почты',
      'invalid_password': 'Пароль должен содержать не менее 8 символов',
      'passwords_dont_match': 'Пароли не совпадают',
      'field_required': 'Это поле обязательно',
      'item_added_to_cart': 'Товар добавлен в корзину',
      'item_removed_from_cart': 'Товар удален из корзины',
      'item_added_to_wishlist': 'Товар добавлен в избранное',
      'item_removed_from_wishlist': 'Товар удален из избранного',
      'order_placed_successfully': 'Заказ успешно размещен',
      'profile_updated': 'Профиль успешно обновлен',
      'password_changed': 'Пароль успешно изменен',

      // Universal App Translations
      'deviceLanguage': 'Язык устройства',
      'appTitle': 'Магазин Сина',
      'settings': 'Настройки',
      'language': 'Язык',
      'farsi': 'Персидский',
      'english': 'Английский',
      'arabic': 'Арабский',
      'russian': 'Русский',
      'chinese': 'Китайский',
      'notifications': 'Уведомления',
      'notificationsEnabled': 'Уведомления включены',
      'cancel': 'Отмена',
      'changeLanguage': 'Изменить язык',
      'error': 'Ошибка',
      'general': 'Общие',
      'connected': 'Подключено',
      'disconnected': 'Отключено',
      'nameLabel': 'Имя',
      'ok': 'OK',
      'default': 'По умолчанию',
      'sort': 'Сортировка',
      'edit': 'Редактировать',
      'delete': 'Удалить',
      'close': 'Закрыть',
      'more': 'Ещё',
      'loading': 'Загрузка...',
      'view': 'Просмотр',
      'name': 'Имя',
      'add': 'Добавить',
      'systemMode': 'Система',
      'dark': 'Тёмный',
      'light': 'Светлый',
      'lightMode': 'Светлый режим',
      'darkMode': 'Темный режим',
      'theme': 'Тема',
      'appTheme': 'Тема приложения',
      'aboutUs': 'О нас',
      'appVersion': 'Версия приложения',
      'yes': 'Да',
      'no': 'Нет',
      'save': 'Сохранить',
      'update': 'Обновить',
      'refresh': 'Обновить',
      'retry': 'Повторить',
      'continue': 'Продолжить',
      'back': 'Назад',
      'next': 'Далее',
      'previous': 'Предыдущий',
      'done': 'Готово',
      'clear': 'Очистить',
      'select': 'Выбрать',
      'selected': 'Выбрано',
      'all': 'Все',
      'none': 'Ничего',
      'filter': 'Фильтр',
      'sort_by': 'Сортировать по',
      'date': 'Дата',
      'privacy_policy': 'Политика конфиденциальности',
      'terms_of_service': 'Условия обслуживания',
      'help_support': 'Помощь и поддержка',
      'about': 'О программе',
      'version': 'Версия',
      'success': 'Успех',
      'warning': 'Предупреждение',
      'info': 'Информация',
      'tryAgain': 'Попробовать снова',
      'unknown': 'Неизвестно',
    },
    'zh': {
      // Shop App Specific
      'app_name': '西娜商店',
      'welcome': '欢迎',
      'login': '登录',
      'register': '注册',
      'logout': '退出登录',
      'email': '电子邮件',
      'password': '密码',
      'confirm_password': '确认密码',
      'forgot_password': '忘记密码？',
      'remember_me': '记住我',
      'dont_have_account': '没有账户？',
      'already_have_account': '已有账户？',
      'sign_up': '注册',
      'sign_in': '登录',
      'home': '首页',
      'products': '产品',
      'categories': '分类',
      'cart': '购物车',
      'wishlist': '愿望清单',
      'profile': '个人资料',
      'search': '搜索',
      'search_products': '搜索产品...',
      'add_to_cart': '添加到购物车',
      'add_to_wishlist': '添加到愿望清单',
      'remove_from_cart': '从购物车中移除',
      'remove_from_wishlist': '从愿望清单中移除',
      'checkout': '结账',
      'orders': '订单',
      'order_history': '订单历史',
      'total': '总计',
      'subtotal': '小计',
      'tax': '税费',
      'shipping': '运费',
      'free_shipping': '免费配送',
      'apply_coupon': '应用优惠券',
      'coupon_code': '优惠码',
      'featured_products': '推荐产品',
      'new_arrivals': '新品',
      'best_sellers': '热销产品',
      'on_sale': '促销中',
      'out_of_stock': '缺货',
      'in_stock': '有库存',
      'quantity': '数量',
      'price': '价格',
      'rating': '评分',
      'reviews': '评论',
      'description': '描述',
      'specifications': '规格',
      'delivery_info': '配送信息',
      'return_policy': '退货政策',
      'size': '尺码',
      'color': '颜色',
      'brand': '品牌',
      'popularity': '受欢迎程度',
      'price_low_to_high': '价格：从低到高',
      'price_high_to_low': '价格：从高到低',
      'newest_first': '最新优先',
      'oldest_first': '最旧优先',
      'no_items_found': '未找到项目',
      'empty_cart': '您的购物车是空的',
      'empty_wishlist': '您的愿望清单是空的',
      'no_orders': '您还没有订单',
      'network_error': '网络错误',
      'something_went_wrong': '出了点问题',
      'please_try_again': '请重试',
      'invalid_email': '请输入有效的电子邮件地址',
      'invalid_password': '密码至少需要8个字符',
      'passwords_dont_match': '密码不匹配',
      'field_required': '此字段为必填项',
      'item_added_to_cart': '商品已添加到购物车',
      'item_removed_from_cart': '商品已从购物车中移除',
      'item_added_to_wishlist': '商品已添加到愿望清单',
      'item_removed_from_wishlist': '商品已从愿望清单中移除',
      'order_placed_successfully': '订单下单成功',
      'profile_updated': '个人资料更新成功',
      'password_changed': '密码更改成功',

      // Universal App Translations
      'deviceLanguage': '设备语言',
      'appTitle': '西娜商店',
      'settings': '设置',
      'language': '语言',
      'farsi': '波斯语',
      'english': '英语',
      'arabic': '阿拉伯语',
      'russian': '俄语',
      'chinese': '中文',
      'notifications': '通知',
      'notificationsEnabled': '通知已启用',
      'cancel': '取消',
      'changeLanguage': '更改语言',
      'error': '错误',
      'general': '通用',
      'connected': '已连接',
      'disconnected': '已断开',
      'nameLabel': '名称',
      'ok': '确定',
      'default': '默认',
      'sort': '排序',
      'edit': '编辑',
      'delete': '删除',
      'close': '关闭',
      'more': '更多',
      'loading': '加载中...',
      'view': '查看',
      'name': '名称',
      'add': '添加',
      'systemMode': '系统',
      'dark': '黑暗',
      'light': '明亮',
      'lightMode': '浅色模式',
      'darkMode': '深色模式',
      'theme': '主题',
      'appTheme': '应用主题',
      'aboutUs': '关于我们',
      'appVersion': '应用版本',
      'yes': '是',
      'no': '否',
      'save': '保存',
      'update': '更新',
      'refresh': '刷新',
      'retry': '重试',
      'continue': '继续',
      'back': '返回',
      'next': '下一个',
      'previous': '上一个',
      'done': '完成',
      'clear': '清除',
      'select': '选择',
      'selected': '已选择',
      'all': '全部',
      'none': '无',
      'filter': '筛选',
      'sort_by': '排序方式',
      'date': '日期',
      'privacy_policy': '隐私政策',
      'terms_of_service': '服务条款',
      'help_support': '帮助与支持',
      'about': '关于',
      'version': '版本',
      'success': '成功',
      'warning': '警告',
      'info': '信息',
      'tryAgain': '重试',
      'unknown': '未知',
    },
  };

  /// Translate a key to the specified language
  static String translate(String key, String languageCode) {
    return _localizedStrings[languageCode]?[key] ?? key;
  }

  /// Get translation for a key
  static String get(String key, String languageCode) {
    return translate(key, languageCode);
  }
}
